\c app;

DROP TABLE IF EXISTS users;

    create table users (
       id VARCHAR(255) NOT NULL PRIMARY KEY,
           username VARCHAR(255) NOT NULL,
           email VARCHAR(255) NOT NULL,
           createdAt TIMESTAMP DEFAULT NOW()
    );

DROP TABLE IF EXISTS movies;

create table movies (
       id int8 generated by default as identity,
        address varchar(255),
        category varchar(255),
        name varchar(255),
        userId VARCHAR(255),
        primary key (id)
    );

DROP TABLE IF EXISTS reviews;

    create table reviews (
       id int8 generated by default as identity,
        content varchar(255),
        movieId int8,
        rating float4,
        userId VARCHAR(255),
        primary key (id)
    );

