name: Test and Deploy
on:
  push:
    branches: [ main ]
jobs:
  native-build:
    name: Build native Quarkus App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
