name: Test and Deploy
on:
  push:
    branches: [ main ]
jobs:
  native-build:
    name: Build native Quarkus App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Build Native with Maven
        run: ./mvnw -B package -Pnative -Dquarkus.native.container-build=true
